### PR TITLE
Initialize Kimai Time Tracking Exporter

### PR DESCRIPTION
**Pull request by Qubasa**
I started implementing an exporter for Kimai Time tracking: https://github.com/kimai/kimai

It's almost finished.

### CODE REVIEW

**Comment by zimbatm** [comment]
Nice. How does it compare to Harvest?

**Comment by zimbatm** [comment]
We could rename the repo to "freelancer-tools" or something. Can you also add the tool to the README?

**Comment by Qubasa** [comment]
@zimbatm It comparse pretty well! UI is a bit different and needs some getting used to.
Interestingly enough Helsinki systems are offering some (paid) addons.

**Comment by Qubasa** [comment]
> We could rename the repo to "freelancer-tools" or something. Can you also add the tool to the README?
Sounds good! Will add it to the README once the implementation is fully done.

**Comment by Qubasa** [comment]
@zimbatm I think this can be merged now

**Pull request merged**
